# Generated by Django 3.0.8 on 2022-07-08 02:44

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('detalhei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizacaoRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalhei.NotaAvaliacao')),
            ],
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pontos_fortes',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pontos_fracos',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Sumario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalhei.Categoria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalhei.Produto')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalhei.NormalizacaoRanking')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizacaoBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nota_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalhei.NotaAvaliacao')),
            ],
        ),
    ]
