# Generated by Django 3.0.8 on 2022-07-08 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detalhei', '0002_auto_20220708_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalizacaobacklog',
            name='nota_avaliacao',
        ),
        migrations.RemoveField(
            model_name='normalizacaoranking',
            name='nota_avaliacao',
        ),
        migrations.AddField(
            model_name='normalizacaobacklog',
            name='avaliacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detalhei.Avaliacao'),
        ),
        migrations.AddField(
            model_name='normalizacaoranking',
            name='avaliacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detalhei.Avaliacao'),
        ),
    ]
