# Generated by Django 3.0.8 on 2022-07-08 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detalhei', '0004_remove_sumario_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumarioNormalizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalhei.Categoria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalhei.Produto')),
            ],
        ),
    ]
