# Generated by Django 3.0.8 on 2022-07-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalhei', '0005_sumarionormalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizacaoranking',
            name='average_score_normalizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='normalizacaoranking',
            name='overall_score_normalizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
