# Generated by Django 4.0.5 on 2022-07-06 04:57

from django.db import migrations

def createMenus(apps, schema_editor):
    Menu = apps.get_model('access', 'Menu')

    menus = [
        # modulo
        Menu(name="Detalhei", path="/detalhei", menu_type="MODULE"),

        # menu
        Menu(name="Cadastros", path="/detalhei/cadastros", menu_type="MENU"),
        
        Menu(name="Cadastros", path="/detalhei/cadastros/cadastros", menu_type="PAGE"),
        Menu(name="Avaliação", path="/detalhei/cadastros/avaliacao", menu_type="PAGE"),
    ]

    Menu.objects.bulk_create(menus)


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(createMenus),
    ]
