# Generated by Django 3.0.8 on 2022-07-07 22:54

from django.db import migrations



def createMenus(apps, schema_editor):
    Menu = apps.get_model('access', 'Menu')

    menus = [
        Menu(name="Ranking", path="/detalhei/ranking", menu_type="MENU"),
        Menu(name="Produto", path="/detalhei/ranking/produto", menu_type="PAGE"),
    ]

    Menu.objects.bulk_create(menus)

class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20220707_0144'),
    ]

    operations = [
        migrations.RunPython(createMenus),
    ]
